/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.financaspessoa.classes;

import com.mycompany.financaspessoa.*;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
public class TelaCalculo extends javax.swing.JFrame {
private final ControladorTelaCalculo controlador;
    public TelaCalculo() {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new ControladorTelaCalculo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSalarioMensal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jGastoLazer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jEconomia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jNegativo = new javax.swing.JTextField();
        jAgua = new javax.swing.JTextField();
        jGastoAlimentacao1 = new javax.swing.JTextField();
        jInternet = new javax.swing.JTextField();
        jErnergia = new javax.swing.JTextField();
        jGastoExtras1 = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/money_2454282.png"))); // NOI18N
        jLabel1.setText("Salario Mensal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jSalarioMensal.setBackground(new java.awt.Color(204, 204, 255));
        jSalarioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalarioMensalActionPerformed(evt);
            }
        });
        getContentPane().add(jSalarioMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 210, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/servico-de-alimentacao (1)_1.png"))); // NOI18N
        jLabel2.setText("Gasto Alimentaçao");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/sun-umbrella_891911.png"))); // NOI18N
        jLabel3.setText("Gasto com Lazer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jGastoLazer.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jGastoLazer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 160, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/agua.png"))); // NOI18N
        jLabel4.setText("Agua");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/light-bulb_900553.png"))); // NOI18N
        jLabel5.setText("Energia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/internet.png"))); // NOI18N
        jLabel6.setText("Internet");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/money_2454282.png"))); // NOI18N
        jLabel7.setText("Gastos Extras");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/calculadora (1).png"))); // NOI18N
        jButton1.setText("Calcular");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 300, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/financaspessoa/salario.png"))); // NOI18N
        jLabel9.setText("Economia");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jEconomia.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jEconomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 180, 20));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel10.setText("Negativo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, 20));

        jNegativo.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jNegativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 190, 20));

        jAgua.setBackground(new java.awt.Color(204, 204, 255));
        jAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAguaActionPerformed(evt);
            }
        });
        getContentPane().add(jAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, 20));

        jGastoAlimentacao1.setBackground(new java.awt.Color(204, 204, 255));
        jGastoAlimentacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGastoAlimentacao1ActionPerformed(evt);
            }
        });
        getContentPane().add(jGastoAlimentacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, 20));

        jInternet.setBackground(new java.awt.Color(204, 204, 255));
        jInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInternetActionPerformed(evt);
            }
        });
        getContentPane().add(jInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 210, 20));

        jErnergia.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jErnergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 160, 20));

        jGastoExtras1.setBackground(new java.awt.Color(204, 204, 255));
        jGastoExtras1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jGastoExtras1KeyPressed(evt);
            }
        });
        getContentPane().add(jGastoExtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 160, 20));
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 161, -1, -1));

        jLabel16.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Calculadora de finanças pessoas");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrador\\Downloads\\fundo tela calculo 6.jpg")); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 780, 390));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Investistimentos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Educacao financeira");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Questionário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalarioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalarioMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalarioMensalActionPerformed

    private void jAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAguaActionPerformed

    private void jGastoAlimentacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGastoAlimentacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGastoAlimentacao1ActionPerformed

    private void jInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInternetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.campovazio();
        controlador.Calculo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        controlador.entrarSistemaInvestimento();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        controlador.entrarSistemaEducacao();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jGastoExtras1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jGastoExtras1KeyPressed
        // TODO add your handling code here:
           if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             controlador.Calculo();
     
      
    }
    }//GEN-LAST:event_jGastoExtras1KeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         controlador.entrarSistemaQuestionario();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public JLabel getImg() {
        return img;
    }

    public void setImg(JLabel img) {
        this.img = img;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculo().setVisible(true);
            }
        });
    }
    
    public JTextField getjAgua() {
        return jAgua;
    }

    public void setjAgua(JTextField jAgua) {
        this.jAgua = jAgua;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JTextField getjEconomia() {
        return jEconomia;
    }

    public void setjEconomia(JTextField jEconomia) {
        this.jEconomia = jEconomia;
    }

    public JTextField getjErnergia() {
        return jErnergia;
    }

    public void setjErnergia(JTextField jErnergia) {
        this.jErnergia = jErnergia;
    }

    public JTextField getjGastoAlimentacao1() {
        return jGastoAlimentacao1;
    }

    public void setjGastoAlimentacao1(JTextField jGastoAlimentacao1) {
        this.jGastoAlimentacao1 = jGastoAlimentacao1;
    }

    public JTextField getjGastoExtras1() {
        return jGastoExtras1;
    }

    public void setjGastoExtras1(JTextField jGastoExtras1) {
        this.jGastoExtras1 = jGastoExtras1;
    }

    public JTextField getjGastoLazer() {
        return jGastoLazer;
    }

    public void setjGastoLazer(JTextField jGastoLazer) {
        this.jGastoLazer = jGastoLazer;
    }

    public JTextField getjInternet() {
        return jInternet;
    }

    public void setjInternet(JTextField jInternet) {
        this.jInternet = jInternet;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getjNegativo() {
        return jNegativo;
    }

    public void setjNegativo(JTextField jNegativo) {
        this.jNegativo = jNegativo;
    }

    public JTextField getjSalarioMensal() {
        return jSalarioMensal;
    }

    public void setjSalarioMensal(JTextField jSalarioMensal) {
        this.jSalarioMensal = jSalarioMensal;
    }
    public void ExibirMensager(String mensagem){
        JOptionPane.showMessageDialog(null,mensagem);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JTextField jAgua;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jEconomia;
    private javax.swing.JTextField jErnergia;
    private javax.swing.JTextField jGastoAlimentacao1;
    private javax.swing.JTextField jGastoExtras1;
    private javax.swing.JTextField jGastoLazer;
    private javax.swing.JTextField jInternet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jNegativo;
    private javax.swing.JTextField jSalarioMensal;
    // End of variables declaration//GEN-END:variables





}
